### ISSUE TITLE
fix: levelDb cannot save BigInts

### ISSUE THREAD

**Issue by ppedziwiatr** [warp-contracts/warp#205]
```
/Users/piotrpedziwiatr/projects/redstone-smartcontracts/node_modules/level-transcoder/lib/formats.js:81
      encode: (data) => Buffer.from(this.encode(data), 'utf8'),
                                         ^
TypeError: Do not know how to serialize a BigInt
    at UTF8Format.stringify (<anonymous>)
    at BufferFormat.encode (/Users/piotrpedziwiatr/projects/redstone-smartcontracts/node_modules/level-transcoder/lib/formats.js:81:42)
    at AbstractSublevel.put (/Users/piotrpedziwiatr/projects/redstone-smartcontracts/node_modules/abstract-level/abstract-level.js:441:39)
    at /Users/piotrpedziwiatr/projects/redstone-smartcontracts/node_modules/abstract-level/abstract-level.js:415:29
    at AbstractSublevel.[undefer] (/Users/piotrpedziwiatr/projects/redstone-smartcontracts/node_modules/abstract-level/abstract-level.js:755:7)
    at /Users/piotrpedziwiatr/projects/redstone-smartcontracts/node_modules/abstract-level/abstract-level.js:168:23
    at Immediate.maybeOpened (/Users/piotrpedziwiatr/projects/redstone-smartcontracts/node_modules/abstract-level/abstract-level.js:138:9)
    at processImmediate (node:internal/timers:471:21)
    ```

**Comment by ppedziwiatr** [comment]
https://github.com/Level/level/issues/221

for now - blocking by default contracts that are using BigInt

**Comment by ppedziwiatr** [comment]
https://github.com/Level/level/issues/221#issuecomment-1211689665 implementing this workaround allows at least to properly catch exception an prevents the DEN from exploding.
