### ISSUE TITLE
bug: [Internal writes] - Cannot read properties of undefined (reading 'manifest'

### ISSUE THREAD

**Issue by koonopek** [warp-contracts/warp#339]
Interaction with error: https://sonar.warp.cc/#/app/interaction/_nQUOzUuJDYz0Ias2oWPgXLK9IOM3maBfeOCW0ckHCE

Same error occurs locally on warp-contracts@1.2.49.

```
TypeError: Cannot read properties of undefined (reading 'manifest') at HandlerBasedContract.createExecutionContext (/home/ubuntu/warp-cache-node/node_modules/warp-contracts/lib/cjs/contract/HandlerBasedContract.js:362:81) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async HandlerBasedContract.readState (/home/ubuntu/warp-cache-node/node_modules/warp-contracts/lib/cjs/contract/HandlerBasedContract.js:118:34) at async CacheableStateEvaluator.doReadState (/home/ubuntu/warp-cache-node/node_modules/warp-contracts/lib/cjs/core/modules/impl/DefaultStateEvaluator.js:104:21) at async CacheableStateEvaluator.eval (/home/ubuntu/warp-cache-node/node_modules/warp-contracts/lib/cjs/core/modules/impl/CacheableStateEvaluator.js:74:16) at async HandlerBasedContract.callContractForTx (/home/ubuntu/warp-cache-node/node_modules/warp-contracts/lib/cjs/contract/HandlerBasedContract.js:482:33) at async HandlerBasedContract.dryWriteFromTx (/home/ubuntu/warp-cache-node/node_modules/warp-contracts/lib/cjs/contract/HandlerBasedContract.js:158:16) at async swGlobal.contracts.write (/home/ubuntu/warp-cache-node/node_modules/warp-contracts/lib/cjs/core/modules/impl/handler/A
```

**Comment by koonopek** [comment]
I don't know how to replicate it, so I will reopen if it happens again, has happend only once
