### ISSUE TITLE
[BUG] Frontend build error starting with version 1.4.30

### ISSUE THREAD

**Issue by arcj0** [warp-contracts/warp#505]
**Describe the bug**
When building with Vue and VITE, there's a node build error.  
```
Error: Build failed with 1 error:
node_modules/warp-contracts/lib/mjs/index.js:1:7: ERROR: No matching export in "node_modules/warp-contracts/bundles/web.bundle.min.js" for import "default"
    at failureErrorWithLog (/Users/joe/Repos/vue-contract-test/node_modules/esbuild/lib/main.js:1624:15)
    at /Users/joe/Repos/vue-contract-test/node_modules/esbuild/lib/main.js:1266:28
    at runOnEndCallbacks (/Users/joe/Repos/vue-contract-test/node_modules/esbuild/lib/main.js:1046:63)
    at buildResponseToResult (/Users/joe/Repos/vue-contract-test/node_modules/esbuild/lib/main.js:1264:7)
    at /Users/joe/Repos/vue-contract-test/node_modules/esbuild/lib/main.js:1377:14
    at /Users/joe/Repos/vue-contract-test/node_modules/esbuild/lib/main.js:678:9
    at handleIncomingPacket (/Users/joe/Repos/vue-contract-test/node_modules/esbuild/lib/main.js:775:9)
    at Socket.readFromStdout (/Users/joe/Repos/vue-contract-test/node_modules/esbuild/lib/main.js:644:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 7,
        file: 'node_modules/warp-contracts/lib/mjs/index.js',
        length: 3,
        line: 1,
        lineText: 'import mod from "../cjs/index.js";',
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'No matching export in "node_modules/warp-contracts/bundles/web.bundle.min.js" for import "default"'
    }
  ],
  warnings: []
}

Node.js v18.16.0
```

**To Reproduce**
You can see the error by running the test repo:  https://github.com/aftrmarket/vue-contract-test
npm run dev

**Desktop (please complete the following information):**
 - OS: MacOs 14.2.1 
 - Node.js version - 18.16.0
 - warp-contracts SDK version 1.4.30 and above
 - warp-contracts plugins being used (+ versions) - 
        "warp-contracts-plugin-deploy": "^1.0.13",
        "warp-contracts-plugin-signature": "^1.0.20"
 - Browser [e.g. chrome, safari] - All browsers

**Comment by dtfiedler** [comment]
@arcj0  - can you test https://github.com/warp-contracts/warp/pull/514 and confirm it works for you?

**Comment by ppedziwiatr** [comment]
@arcj0 , can you please try with `1.4.42` ?
